version: "3.9"

services:
  database:
    image: postgres
    container_name: database_deliveries
    restart: always    
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/data/postgres
      
volumes:
  pgdata:
    driver: local
